# version: '3.1'

services:
  app:
    container_name: fake-store-api
    build: .
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - /etc/letsencrypt/live/fakestoreapi.shayanaryan.com:/etc/letsencrypt/live/fakestoreapi.shayanaryan.com:ro
    # depends_on:
      # - db
  # db:
  #   image: mongo
  #   restart: always
  #   volumes:
  #     - ./mongo_data:/data/db
  #   env_file:
  #     - .env
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME?MongoDB username}
  #     MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD?MongoDB password}